title: MinJune Kim
email: rnrmf1121@gmail.com
description: Personal homepage of MinJune Kim.
url: "https://minjuune.github.io"
baseurl: ""
lang: en

include:
  - _pages
  - assets
  - .nojekyll

exclude:
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor
